# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(40, 30, 521, 351))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("crack.jpg"))
        self.image.setObjectName("image")
        self.crack_btn = QtWidgets.QPushButton(self.centralwidget)
        self.crack_btn.setGeometry(QtCore.QRect(90, 450, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.crack_btn.setFont(font)
        self.crack_btn.setObjectName("crack_btn")
        self.pothole_btn = QtWidgets.QPushButton(self.centralwidget)
        self.pothole_btn.setGeometry(QtCore.QRect(400, 450, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pothole_btn.setFont(font)
        self.pothole_btn.setObjectName("pothole_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pothole_btn.clicked.connect(self.pothole_show)
        self.crack_btn.clicked.connect(self.crack_show)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.crack_btn.setText(_translate("MainWindow", "Crack"))
        self.pothole_btn.setText(_translate("MainWindow", "Pothole"))

    def crack_show(self):
        self.image.setPixmap(QtGui.QPixmap("crack.jpg"))
    
    def pothole_show(self):
        self.image.setPixmap(QtGui.QPixmap("potholes.jpg"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
