# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lineandtext.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 70, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(190, 150, 181, 121))
        self.textEdit.setObjectName("textEdit")
        self.lineedit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.lineedit_btn.setGeometry(QtCore.QRect(90, 340, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineedit_btn.setFont(font)
        self.lineedit_btn.setObjectName("lineedit_btn")
        self.textedit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.textedit_btn.setGeometry(QtCore.QRect(370, 340, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textedit_btn.setFont(font)
        self.textedit_btn.setObjectName("textedit_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.lineedit_btn.clicked.connect(self.show_line)
        self.textedit_btn.clicked.connect(self.show_textedit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineedit_btn.setText(_translate("MainWindow", "Line"))
        self.textedit_btn.setText(_translate("MainWindow", "Text Edit"))

    def show_line(self):
        print(self.lineEdit.text())
    
    def show_textedit(self):
        print(self.textEdit.toPlainText())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
